---
title: "Data Project"
author: "Ally Rakus"
date: "6/22/2020"
output: github_document
---

Calling the packages 
```{r message=FALSE}
library(dplyr) # manipulate dataframes
library(readr) # read/write dataframes
library(ggplot2) # making plots
```

Import the crime data and reformat the date into the R date type (Y-M-D)
```{r}
library(readr)
library(fs)

bmore_crime_data_6_22 <- read_csv(path("bmore crime data_6_22.csv"),
 col_types = cols(
   CrimeDate = col_date(format = "%m/%d/%Y")
 )
)

bmore_crime_data_6_22

```

Filtering for incidents that occurred in years that match the census data (2014-2018)
```{r}
bmore_crime_data_2014_2018 <- filter(bmore_crime_data_6_22, between(CrimeDate, as.Date("2014-01-01"),as.Date("2018-12-31")))

bmore_crime_data_2014_2018
```

Removing duplicate rows 
```{r}
library(janitor)
bmore_crime_data_2014_2018 %>% get_dupes

```

Filtering for incidents considered to be property crime 
```{r}
bmore_property_crime_2014_2018 <- filter(bmore_crime_data_2014_2018, Description %in% c("BURGLARY", "LARCENY", "LARCENY FROM AUTO", "AUTO THEFT", "ARSON", "ROBBERY - STREET", "ROBBERY - CARJACKING", "ROBBERY - COMMERICAL", "ROBBERY - RESIDENCE")
)

bmore_property_crime_2014_2018
```

Assigning a unique ID to each obs
```{r}
bmore_property_crime_2014_2018 %>% mutate(id = row_number())
```

Getting rid of incidents without coordinates/lat-long data
```{r}
bmore_property_crime_2014_2018 %>% 
  filter(!Longitude == "NA") %>% 
  filter(!Latitude == "NA")

```





